In [1]:
import numpy as np
import pandas as pd

### Data type of NumPy, 
- Main datatyp of NumPy is ndarray

In [2]:
array1 = np.array([1,2,3,4,5,6,7])

In [3]:
array1

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2 = np.array([
                    [1, 2.2, 3.3],
                    [4, 5, 7.5]
                ])
array2

array([[1. , 2.2, 3.3],
       [4. , 5. , 7.5]])

In [6]:
array3 = np.array([
                    [[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]], 
                    
                    [[10, 11, 12],
                     [13, 14, 15], 
                     [16, 17, 18]]
                ])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
array1.shape, array2.shape, array3.shape

((7,), (2, 3), (2, 3, 3))

## Axis = direction

1. (7,) = 01 Axis, seven elements along the axis
2. (2,3) = 02 axes (1 row and 1 column), 2 elements in first axis, and 3 elements in 2nd axis
3. (2, 3, 3) = 03 axis (2 blocks, 3 rows in each block, 3 columns in each block)

In [8]:
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [9]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
array1.size, array2.size, array3.size

(7, 6, 18)

In [11]:
type(array1), type(array2), type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [43]:
dataframe = pd.DataFrame(array2)
dataframe

,0,1,2
0,1.0,2.2,3.3
1,4.0,5.0,7.5


In [13]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
array_range = np.arange(0, 13, 3)
array_range

array([ 0,  3,  6,  9, 12])

In [16]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [17]:
random_array

array([[8, 5, 6, 5, 7],
       [2, 3, 9, 6, 5],
       [4, 4, 6, 6, 9]], dtype=int32)

In [18]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.65566333, 0.3106813 , 0.05033075],
       [0.63145651, 0.17763596, 0.96402019],
       [0.57929975, 0.94630641, 0.5179921 ],
       [0.17690747, 0.11208062, 0.64663934],
       [0.7628189 , 0.08944623, 0.96858263]])

In [19]:
random_array3 = np.random.rand(5, 3)

In [20]:
random_array3

array([[0.66981299, 0.01503496, 0.32898703],
       [0.59472208, 0.68356652, 0.61267516],
       [0.4982788 , 0.08700854, 0.4353416 ],
       [0.04177417, 0.26619096, 0.59512727],
       [0.67495701, 0.65628147, 0.86211608]])

In [21]:
np.random.seed(10)
newrandomarray = np.random.rand(5,4)
newrandomarray

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

### Viewing arrays and matrices

In [22]:
np.unique(random_array)

array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [23]:
array1

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
array2

array([[1. , 2.2, 3.3],
       [4. , 5. , 7.5]])

In [25]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
array1[0]

np.int64(1)

In [27]:
array2[0]

array([1. , 2.2, 3.3])

In [28]:
array3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [30]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
array3[:2, :3, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [32]:
nparray = np.random.randint(10, size=(2,3,4,5))
nparray

array([[[[3, 9, 6, 9, 1],
         [9, 4, 2, 6, 7],
         [8, 8, 9, 2, 0],
         [6, 7, 8, 1, 7]],

        [[1, 4, 0, 8, 5],
         [4, 7, 8, 8, 2],
         [6, 2, 8, 8, 6],
         [6, 5, 6, 0, 0]],

        [[6, 9, 1, 8, 9],
         [1, 2, 8, 9, 9],
         [5, 0, 2, 7, 3],
         [0, 4, 2, 0, 3]]],


       [[[3, 1, 2, 5, 9],
         [0, 1, 0, 1, 9],
         [0, 9, 2, 1, 1],
         [0, 0, 5, 9, 0]],

        [[4, 6, 6, 0, 2],
         [3, 3, 2, 6, 0],
         [5, 1, 3, 6, 5],
         [5, 1, 8, 0, 5]],

        [[9, 8, 5, 7, 8],
         [5, 8, 9, 9, 1],
         [5, 9, 1, 4, 7],
         [7, 7, 9, 7, 6]]]], dtype=int32)

In [33]:
nparray.ndim

4

In [34]:
nparray[0, 0, :, :]

array([[3, 9, 6, 9, 1],
       [9, 4, 2, 6, 7],
       [8, 8, 9, 2, 0],
       [6, 7, 8, 1, 7]], dtype=int32)

### Manipulating and Comparing arrays

In [35]:
array1

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
ones=np.ones(7)
ones

array([1., 1., 1., 1., 1., 1., 1.])

In [37]:
array1 + ones

array([2., 3., 4., 5., 6., 7., 8.])

In [38]:
array1 - ones

array([0., 1., 2., 3., 4., 5., 6.])

In [39]:
array1 * ones

array([1., 2., 3., 4., 5., 6., 7.])

In [40]:
array1, array2

(array([1, 2, 3, 4, 5, 6, 7]),
 array([[1. , 2.2, 3.3],
        [4. , 5. , 7.5]]))

In [44]:
array1 * array2

ValueError: operands could not be broadcast together with shapes (7,) (2,3) 

In [45]:
array1 = np.array([2, 3, 4])
array1

array([2, 3, 4])

In [46]:
array2

array([[1. , 2.2, 3.3],
       [4. , 5. , 7.5]])

In [47]:
array1 * array2

array([[ 2. ,  6.6, 13.2],
       [ 8. , 15. , 30. ]])

In [48]:
array1.shape, array2.shape

((3,), (2, 3))

In [49]:
ones = np.ones(3)

In [50]:
ones

array([1., 1., 1.])

In [51]:
array1/ones

array([2., 3., 4.])

In [52]:
array1 / array2

array([[2.        , 1.36363636, 1.21212121],
       [0.5       , 0.6       , 0.53333333]])

In [53]:
array1 // array2

array([[2., 1., 1.],
       [0., 0., 0.]])

In [54]:
array2 ** 2


array([[ 1.  ,  4.84, 10.89],
       [16.  , 25.  , 56.25]])

In [55]:
np.square(array1)

array([ 4,  9, 16])

In [56]:
newarray=np.add(array1, ones)

In [57]:
np.exp(newarray)

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [58]:
listsample = [2,4,6]
type(listsample)

list

In [59]:
sum(listsample)

12

In [60]:
array1

array([2, 3, 4])

In [61]:
np.sum(array1)

np.int64(9)

In [ ]:
# when to use sum() vs np.sum()
# use sum() on python data types, and use np.sum() on np data types.

In [62]:
big_array = np.random.random(50000)

In [63]:
big_array[:20]

array([0.24846698, 0.32714403, 0.00291609, 0.29544213, 0.98688912,
       0.23833271, 0.73339648, 0.96219689, 0.81545579, 0.69422698,
       0.21069609, 0.51784407, 0.94966999, 0.69597387, 0.90466474,
       0.64789243, 0.34530215, 0.06549786, 0.22062786, 0.13737325])

In [64]:
%timeit sum(big_array)
%timeit np.sum(big_array)

4.76 ms ± 280 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.4 μs ± 3.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [65]:
np.mean(big_array)

np.float64(0.49968139383147575)

In [66]:
np.max(big_array), np.min(big_array)

(np.float64(0.9999853400536635), np.float64(1.5108738395275267e-05))

In [67]:
np.std(big_array)

np.float64(0.2892566339821243)

In [68]:
variance1 = np.array([100, 200, 400, 4000, 8000])
variance2 = np.array([2, 4, 6, 8, 10])

In [69]:
np.var(variance1), np.var(variance2)

(np.float64(9590400.0), np.float64(8.0))

In [70]:
np.std(variance1), np.std(variance2)

(np.float64(3096.8370961353457), np.float64(2.8284271247461903))

In [71]:
np.mean(variance1), np.mean(variance2)

(np.float64(2540.0), np.float64(6.0))

 ### Reshaping and Transposing

In [72]:
array3.shape, array2.shape

((2, 3, 3), (2, 3))

In [73]:
array2 * array3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [74]:
array2 = array2.reshape(2,3,1)

In [75]:
array2

array([[[1. ],
        [2.2],
        [3.3]],

       [[4. ],
        [5. ],
        [7.5]]])

In [76]:
array2.shape, array3.shape

((2, 3, 1), (2, 3, 3))

In [77]:
array2 * array3

array([[[  1. ,   2. ,   3. ],
        [  8.8,  11. ,  13.2],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [120. , 127.5, 135. ]]])

In [78]:
array2.shape

(2, 3, 1)

In [79]:
array2 = array2.T

In [80]:
array2.shape

(1, 3, 2)

In [81]:
array2

array([[[1. , 4. ],
        [2.2, 5. ],
        [3.3, 7.5]]])

In [84]:
np.random.seed(1)

matrix1 = np.random.randint(5, size=(5, 3))
matrix2 = np.random.randint(10, size=(5, 3))

In [83]:
matrix1

array([[3, 4, 0],
       [1, 3, 0],
       [0, 1, 4],
       [4, 1, 2],
       [4, 2, 4]], dtype=int32)

matrix1 * matrix2

In [85]:
matrix1 * matrix2 # element-wise multiplication

array([[ 6, 16,  0],
       [ 7, 27,  0],
       [ 0,  0, 24],
       [36,  9, 14],
       [24, 18,  4]], dtype=int32)

In [86]:
np.dot(matrix1, matrix2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [87]:
matrix1=matrix1.T

In [88]:
np.dot(matrix1, matrix2)

array([[73, 93, 54],
       [57, 70, 46],
       [70, 54, 42]], dtype=int32)

# Comparison opertor

In [89]:
result = array1 >= ones
result

array([ True,  True,  True])

In [90]:
type(result)

numpy.ndarray

In [91]:
ones == 1

array([ True,  True,  True])

In [92]:
array5 = np.random.randint(9, size=(4, 6))
array5

array([[0, 1, 8, 8, 3, 8],
       [7, 3, 6, 5, 1, 3],
       [4, 8, 1, 4, 0, 3],
       [2, 0, 4, 2, 7, 7]], dtype=int32)

In [93]:
np.sort(array5)

array([[0, 1, 3, 8, 8, 8],
       [1, 3, 3, 5, 6, 7],
       [0, 1, 3, 4, 4, 8],
       [0, 2, 2, 4, 7, 7]], dtype=int32)

In [94]:
np.argsort(array5)

array([[0, 1, 4, 2, 3, 5],
       [4, 1, 5, 3, 2, 0],
       [4, 2, 5, 0, 3, 1],
       [1, 0, 3, 2, 4, 5]])

In [95]:
np.argmin(array5)

np.int64(0)

In [96]:
np.argmax(array5)

np.int64(2)

In [97]:
array5

array([[0, 1, 8, 8, 3, 8],
       [7, 3, 6, 5, 1, 3],
       [4, 8, 1, 4, 0, 3],
       [2, 0, 4, 2, 7, 7]], dtype=int32)

In [98]:
np.argmin(array5, axis=0)

array([0, 3, 2, 3, 2, 1])

In [99]:
np.argmin(array5, axis=1)

array([0, 4, 4, 1])

## converting image to numpy array

In [ ]:
from IPython.display import Image
Image("parrot.jpg")

In [ ]:
from matplotlib.image import imread

parrot = imread ("parrot.jpg")

In [ ]:
type(parrot)

In [ ]:
parrot

In [ ]:
parrot.shape

In [ ]:
parrot.size

In [ ]:
parrot.ndim

### importing ECG data as a numpy array

In [ ]:
ecg = np.loadtxt("mitbih_train.csv", delimiter=",")

In [ ]:
print(ecg.shape)

In [ ]:
print(ecg.ndim)

In [ ]:
print(ecg.dtype)

In [ ]:
ecg[0]

In [ ]:
ecg[0,16]

In [ ]:
mean_signal = np.mean(ecg, axis=0)
mean_signal

In [ ]:
mean_signal.shape

In [ ]:
std_per_patient = np.std(ecg, axis=1)

In [ ]:
std_per_patient

In [ ]:
std_per_patient.shape

In [ ]:
min_vals = np.min(ecg, axis=1)
max_vals = np.max(ecg, axis=1)

In [ ]:
min_vals

In [ ]:
min_vals.shape

In [ ]:
max_vals

In [ ]:
max_vals.shape

In [ ]:
ecg.shape

## Normalization in Numpy

In [ ]:
X = ecg[:, :187]   # features
y = ecg[:, 187]    # target

In [ ]:
mean_per_row = np.mean(X, axis=1, keepdims=True)
std_per_row  = np.std(X, axis=1, keepdims=True)

In [ ]:
mean_per_row.shape, std_per_row.shape

In [ ]:
X_norm = (X - mean_per_row) / std_per_row

In [ ]:
X_norm.shape

In [ ]:
np.mean(X_norm, axis=1)

In [ ]:
np.std(X_norm, axis=1)